Controllers/GlobalController.cs
using System.IO;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using nexus_connect.Data;
using nexus_connect.Data.Entities;
using nexus_connect.ViewModels;
using nexus_connect.Data.DTO;

namespace nexus_connect.Controllers
{

    public class GlobalController : Controller
    {
        private readonly ILogger<GlobalController> _logger;
        readonly UserManager<StoreUser> _userManager;
        readonly IMapper _mapper;
        readonly INexusConnectRepository _repository;
        public GlobalController(ILogger<GlobalController> logger, UserManager<StoreUser> userManager, IMapper mapper, INexusConnectRepository repository)
        {
            _repository = repository;
            _userManager = userManager;
            _logger = logger;
            _mapper = mapper;
        }

        public async Task<IActionResult> MyAccount(MyAccountViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            return PartialView("MyAccount", _mapper.Map<MyAccountViewModel>(user));
        }
        public async Task<IActionResult> Notifications(NotificationViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            var notifiactions = await _repository.GetNotifcations(user.Id);
            return PartialView("Notifications", notifiactions);
        }
        [HttpPost]
        [Route("/Global/Notifications/mark-as-read")]
        public async Task<IActionResult> NotificationsMarkAsRead([FromBody] MarkNotificationDto model)
        {
            Console.WriteLine("##################################### SQL ####################");
            Console.WriteLine(model.Id);
            Console.WriteLine("##################################### SQL ####################");
            if (await _repository.SetNotifyAsRead(model.Id))
            {
                return Ok();
            }
            return NotFound();
        }
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

Views/Shared/_AnonymousLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nexus_connect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/nexus_connect.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">nexus_connect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
             @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - nexus_connect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nexus_connect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/nexus_connect.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">nexus_connect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index">@User.Identity.Name</a>
                        </li>
                        }else{
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Login">Login</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - nexus_connect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoggedLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nexus_connect</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/nexus_connect.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">nexus_connect</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index">@User.Identity.Name</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="p-2">
            <div class="row">
                <div class="col-2 p-2" style="min-width: 15rem;">
                @if(IsSectionDefined("LeftSideBar")){
                    @RenderSection("LeftSideBar", required: false)
                }else{
                    <div class="card" style="width: 100%;">
                        <div class="card-header">
                            Context Menu
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><a  id="openModalLink-MyAccount" asp-controller="Global" asp-action="Myaccount" class="">My Account</a></li>
                            <li class="list-group-item"><a  id="openModalLink-Notifications" asp-controller="Global" asp-action="Notifications">Notifications</a><span class="badge badge-danger" style="background-color: red;">4</span></li>
                            <li class="list-group-item"><a href="#" class="">Dashboard</a></li>
                        </ul>
                    </div>
                }
                </div>
                <div class="col-8 p-2">
                    @RenderSection("MainContainer", required:true)
                </div>
            </div>
        </main>
    </div>
     <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Modal Content</h3>
            <div id="modalContentPlaceholder"></div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - nexus_connect - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>